### ISSUE TITLE
EXIF GPS data not read

### ISSUE THREAD

**Issue by mrcolj** [xbgmsharp/piwigo-openstreetmap#109]
Sorry for the strange title, but I thought it was appropriate.

So I just uploaded 40 photos.  I've been using piwigo/OSM for at least a year and have had no problems.  Then a moment ago, after a few photos, it imported the rest with no GPS data.  The rest of the EXIF is still there, just no pins on the map.  I deleted an reimported the photos, same thing.  I added the GPS data manually on one and it worked fine.

I'm on current Piwigo with current OSM street map.

Thoughts?

**Comment by xbgmsharp** [comment]
Since PWG 2.6, OSM does not manage anymore the EXIF GPS data. It is a PWG built-in feature. 
http://piwigo.org/doc/doku.php?id=dev:changes_in_2.6#gps_metadata

So your issue is not link to OSM plugin. Happy to help, but I would need more details to help and potentially solve the issue. Could you provide a working image and a non working image.

**Comment by mrcolj** [comment]
Thank you!  

1. [working](http://www.colinandbethany.com/photos/picture.php?/11710/category) - outside my office window at 6pm are 50+ Pokemon GO players every night...
2. [not working](http://www.colinandbethany.com/photos/picture.php?/11729/category/193) - at a drive in movie...
3. [this one I added the info manually](http://www.colinandbethany.com/photos/picture.php?/11730/category/193) - my kids waiting for the drive-in movie to start...

Now that I put that, the only one from that folder that worked was the panorama, so maybe the excessive size or dimensions (it was originally 15 MB and 25-something megapixels) broke it.  If you go into the previous folder (June 2016), all of those worked, and in the August folder none of them worked.

Thank you for your help!

**Comment by xbgmsharp** [comment]
I would make sure the image have GPS data. Nothing have change in this regards as it is a PWG core feature. You can use exiftool or other to extract the information out of it.

**Comment by mrcolj** [comment]
Confirmed.  They all have GPS data, all taken off the same phone.  Actually the one I added in manually I added from the original's EXIF data.  But when I uploaded it, it was stripped.  The other exif data, at least the date and time, were still there--but the GPS data shows as not being there in PWG.

**Comment by mrcolj** [comment]
These are the plugins I have installed.  Again I don't think I've changed anything lately, but I may have and not remember, or of course they all get updated so there may be a compatibility thing there...
![screen shot 2016-08-04 at 1 27 23 pm](https://cloud.githubusercontent.com/assets/364364/17413581/6955e5f4-5a47-11e6-9fe9-206b921db4cd.png)

**Comment by mrcolj** [comment]
Okay, I just uploaded from the Piwigo app and no GPS data.  The photo definitely has data.

**Comment by keefian** [comment]
Hi,
It seems I have the same problem :-(
I have just installed Piwigo (latest version) on a debian remote server. I have installed both "RV Maps&Earth" and "OpenStreetMap" plugins and uploaded some geotagged pics for testing.
And none of the pictures appeared on the map.
I tried to synchronize the metadata and reimport the pictures but it didn't have any effect.

I did the test the other way round : I downloaded the pictures from piwigo just to see if the GPS had been removed during the import. Once downloaded from Piwigo the GPS data were still there (could see them on Picasa).

For what it's worth I used the GeoSetter soft to create the GPS data.

**Comment by xbgmsharp** [comment]
As mention the  GPS data parsing is done via PWG core and as you point out "RV Maps&Earth" and "OpenStreetMap" plugins would have the same issue.

I took a photo using my iPhone6 on iOS 9.3 and just try using PWG 2.8.2, Uploading a photo via the ``Upload photos [Web Form]`` method and the EXIF data is being parse. Once uploaded, you click on the thumbnail and then ``OpenStreetMap`` Tab and you should see ``Latitude`` and ``Longitude`` in the ``Properties`` section as well as the map.

To continue debug, please edit the file ``tools/metadata.php`` and update the line ```$filename = 'sample.jpg';``` to the select image. Then from your web-browser you should see all the metadata correctly read by PWG.
Or Could you send me by email a photo with GPS data?

**Comment by keefian** [comment]
Thank you for your response.

I did what you suggested :
- uploaded the photo : no data properties set on the OpenStreetMap tab
- when looking at the EXIF info via the metadata.php script I can retrieve the GPS data : 
```
### Informations are read from photo1.jpg
IPTC Fields in photo1.jpg
2#000 = 
2#025 = Bretagne,FRA,France,geo:lat=48.67464008,geo:lon=-3.84555817,geotagged,Kerbabu,Plougasnou
2#055 = 20160124
2#060 = 175358+0100
2#080 = Picasa
2#090 = Plougasnou
2#092 = Kerbabu
2#095 = Bretagne
2#100 = FRA
2#101 = France
```
So I did another test with a picture shot with another camera. I set the EXIF GPS tag using GeoSetter soft so that both pictures had exactly the same info.
I uploaded the picture on PWG and this time everything is fine : the GPS data are displayed on the OpenStreetMap tab.
Here are the info retrieved by the metadata.php script : 
```
Informations are read from photo2.jpg
IPTC Fields in photo2.jpg
2#000 = 
2#025 = geo:lat=48.67464008,geo:lon=-3.84555817,geotagged,Bretagne,FRA,France,Kerbabu,Plougasnou
2#055 = 20130310
2#060 = 123613+0000
2#090 = Plougasnou
2#092 = Kerbabu
2#095 = Bretagne
2#100 = FRA
2#101 = France
```
I noticed that there is a difference in the 2#025 tag between the 2 pictures : information are not filled in the same order. Could it the cause of the problem ?

When I set the GPS info on GeoSetter I did it in batch mode so that both pictures have the same info. Also when I open the pictures via FastStone Image Browser, the GPS tags are correctly retrieved and diplayed for both pictures.

I have attached the 2 pictures : 
[photo.zip](https://github.com/xbgmsharp/piwigo-openstreetmap/files/428225/photo.zip)

**Comment by xbgmsharp** [comment]
I just try with both of your photo and PWG read correctly the IPTC Fileds. I am not able to reproduce the issue.

**Comment by keefian** [comment]
Hi,

Thank you for your effort?

Can I give you access to my PWG server ?

http://37.59.37.124/piwigo
user : test
pwd : test





2016-08-20 12:33 GMT+02:00 xbgmsharp <notifications@github.com>:

**Comment by xbgmsharp** [comment]
I connect to you PWG instance and uploaded the photo you provide and it works fine.
http://37.59.37.124/piwigo/admin.php?page=plugin&section=piwigo-openstreetmap/admin/admin_photo.php&image_id=17

**Comment by keefian** [comment]
Thanks again

Just to be sure : did you upload both photos ? (I only see one : photo2.jpg)
Indeed as I mentionned in my previous comment, the 2nd photo I shot with my
second camera (photo2.jpg) works fine. That's the first one (photo1.jpg)
that I have problem with.

**Comment by xbgmsharp** [comment]
I confirm when that uploading photo1 to you PWG, it does not read the GPS data.
However both photo works with my PWG, so there must be something different.
In my config I have both IPTC settings to ``false`` , ``$conf['show_iptc'] = false;`` and  ``$conf['use_iptc'] = false;``
However I have both EXIF settings to ``true`` , ``$conf['show_exif'] = true;`` and  ``$conf['use_exif'] = true;``
I must admit, I am out of idea. I would recommend to raise an issue to PWG.

**Comment by keefian** [comment]
Thanks again for your time.

I will try to re-install PWG (maybe I did something wrong when I first
installed it).

2016-08-25 16:42 GMT+02:00 xbgmsharp <notifications@github.com>:

**Comment by keefian** [comment]
I re-installed my server and PWG but I am still facing the same problem.

So as suggested I raised an issue to PWG : 
[https://github.com/Piwigo/Piwigo/issues/520](url)

**Comment by wittypluck** [comment]
Hello,
I upgraded from php 7.0.8 to 7.0.10 (on Ubuntu server 16.04) which seemed to fix the issue for me.
See https://github.com/Piwigo/Piwigo/issues/520

**Comment by xbgmsharp** [comment]
Great news thanks for the update.
