### ISSUE TITLE
Gateway Timeout when tagging

### ISSUE THREAD

**Issue by JD4x4** [xbgmsharp/piwigo-openstreetmap#110]
I'm a new user, so forgive me if I'm overlooking something..
I have several thousand photos with exif geodata, and ran OpenStreetMap City and State tagging on them shortly after uploading, but roughly 2/3rds of them have not returned a tag although all but a handful have maps (so I know they've gone through the plugin and been identified for coordinates).

Now when I run tagging on them, after about 3 to 5 minutes I get "Gateway Timeout- The gateway did not receive a timely response from the upstream server or application."

Is there something I can change in php to allow more processing time? Is this a problem with OpenStreetMap plugin? Do I need to somehow process my images in smaller batches?  Any help is greatly appreciated. Using the latest Pwigo and OpenStreetMap versions, running on a 1and1 web site host with PHP 5.6

**Comment by xbgmsharp** [comment]
OpenStreetMap Nominatim (http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) is limited to 1 request a second. By default you are using my proxy, https://nominatim-xbgmsharp.rhcloud.com to cache response. Try to do the tagging by smaller batch. 
If you wish you could use the alternative mapquestapi.com which require a API key.

**Comment by JD4x4** [comment]
Thank you for the quick reply. I suspected that since I've done a similar reverse geocode using google maps. I'm not very well versed in php, but should it be possible to add a delay loop somewhere?

Otherwise, I'll try to split my photos into smaller albums, and once geocoded merge them back.
