### ISSUE TITLE
'Find my position' gives user error - for ever

### ISSUE THREAD

**Issue by IanMac900** [xbgmsharp/piwigo-openstreetmap#111]
Hi I really appreciate this plug-in - it's great and most useful - thanks very much.
However I got an old lady to click on the plug-in and she and now I cannot ever use the 'Find my position' facility again. Having selected not to make user's location public - the error message 'Geolocation error. User denied geolocation prompt" seems to be retained until the user's dieing day!  This is not user friendly and there should be a way to select another choice from the menu.
However why does the user's position have to be made public?  I can understand why my friend chose that selection and surely others will also.  She won't use the plug-in again, until I get you to fix this.
Please look at this again.

**Comment by xbgmsharp** [comment]
Hello,

Could you please clarified? There is nothing in the plugin about making ``user's location public``. The feature ``Find my position`` allow to locate yourself, it is never share anywhere or track at all.
To my understanding,  it seems you disallow the use of location and now you are trying to turn it back on. This is a browser user error. After a quick google search here is how to sove it on Firefox. https://www.mozilla.org/en-US/firefox/geolocation/
```
How do I undo a permission granted to a site?

If you've given Firefox permission to always give your location to a site and later change your mind, you can easily revoke that permission. Here's how:

    Navigate to the site to which you’ve given permission
    Go to the Tools menu, then select Page Info
    Select the Permissions tab
    Change the setting for Share Location

```

**Comment by IanMac900** [comment]
On clicking on 'Find my position' **initially** a menu is shown, containing three choices.  I cannot say exactly what these are now because after I clicked on of them the error message 'Geolocation error. User denied geolocation prompt" results - forever.  I have done what you suggested and the FireFox information is now well out of date [not your fault, I know], but I managed to work out how to find a list of permissions for the webpage in question.  I had to take a photo of the page since the dialogue box disappeared when I tried to screen-grab it.  The message says that there are no special permissions for the page.  I have reset the computer and still get the same error message as detailed on my first message.
![geolocation denial](https://cloud.githubusercontent.com/assets/19530241/17831163/94a614a6-66d9-11e6-86b4-bbb9dadbb941.PNG)
I don't consider the matter closed.
The attachments show the page Info:-
![5492](https://cloud.githubusercontent.com/assets/19530241/17831061/42e693b8-66d7-11e6-9448-f835a88f22c1.jpg)
![firefox page info -general](https://cloud.githubusercontent.com/assets/19530241/17831062/4cbb9cf8-66d7-11e6-8745-9e6c4a697547.PNG)
![firefox page info -security](https://cloud.githubusercontent.com/assets/19530241/17831064/5094c390-66d7-11e6-8e4c-307c8523a936.PNG)

**Comment by xbgmsharp** [comment]
Again this is an issue with your browser. I did block the geolocation and got the same error message. Then on page info, I could see the permissions settings. The FireFox information is not out of date.
Until you change the permission on the page, you will see this popup.
``Geolocation error. User denied geolocation prompt``

If you want to remove the message, comment or remove the following line.
https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/template/osm-map2.tpl#L543

<img width="772" alt="screen shot 2016-08-20 at 2 17 47 pm" src="https://cloud.githubusercontent.com/assets/1498985/17831456/062c11be-66e1-11e6-9d33-4f9885f34f5e.png">

**Comment by IanMac900** [comment]
Thank you for taking the time to explain this to me.  I was trying to remember the menu but now know where to look:-
![5493](https://cloud.githubusercontent.com/assets/19530241/17832656/18dbe432-6700-11e6-9d1b-ec8b969c9481.jpg)
Yes, the browser's notice invites you to learn more and that's what I should have done.  I now know that it's not going to share my location with the general public but only with my copy of the browser.
However having got over that problem, by selecting the 'Always Share Location' option, selecting 'Find my position' comes up with 'Position acquisition timed out' and the displayed map is centred on Beverley which is about 8 miles [13km] north of Swanland. 
![position acquisition timed out](https://cloud.githubusercontent.com/assets/19530241/17832720/7257cb2e-6701-11e6-90e2-5b2e7aef60d9.PNG)
The second time I tried this the error did not occur, but the map displayed the same information.
I have already setup the map to be centred on Swanland, so since the website is only about the village of Swanland, our users don't want to be confused by the 'Find my position' facility.  Could you supply the administrator who sets up the plug-in with a switch which would instruct the 'Find my position' software just use the OS co-ordinates already setup - in this case those of Swanland?
I must emphasise that I have been delighted with the plug-in which already has been most useful and will continue to be so.  Thank you very much for supplying it.
