### ISSUE TITLE
Display of map in Category's description, if co-ordinates of some photos are both zero

### ISSUE THREAD

**Issue by IanMac900** [xbgmsharp/piwigo-openstreetmap#112]
In having over 2000 photos on the website of a very small land area, I do not wish the location pointer of those photos having both zero co-ordinates (by default) to be displayed (causing a view of the whole earth to be shown, with the blue location pointer in the Atlantic Ocean on the equator - see attachment
![zero co-ords display](https://cloud.githubusercontent.com/assets/19530241/17858561/17926bb2-687e-11e6-9cb0-37e93026659b.PNG)
).
How can I achieve this with the plug-in?

**Comment by xbgmsharp** [comment]
There is no zero co-ordinates by default. You more likely edit the photo and save the settings.
If you remove the value and make both fields (latitude and longitude) empty, it will remove the any value

**Comment by IanMac900** [comment]
No, maybe it's the browser (Firefox) again but when both boxes are cleared of zeros the zeros re-emerge to give the unwanted display in the Atlantic Ocean.  I have even tried spaces, but the zeros come back when the 'Save Settings' button is pressed.
![coords are zeroed](https://cloud.githubusercontent.com/assets/19530241/17859647/59bc56a2-6882-11e6-9f30-89a47a286ac2.PNG)
![coords are blank](https://cloud.githubusercontent.com/assets/19530241/17859646/5980acce-6882-11e6-86c2-6572c67d2440.PNG)

**Comment by xbgmsharp** [comment]
Correct by default the input fields with display 0 if nothing as to display on the map below it require default which are set to 0. Make the input field empty and save, it will reset the value.

**Comment by IanMac900** [comment]
As shown above I do make the input fields both empty (see attachment above), but when I press the 'Save Settings' button the zeros re-emerge in the boxes and the location pointer is in the Atlantic.

**Comment by xbgmsharp** [comment]
As mention is correct as per the admin page I need data to display the map. so it always revert to 0 however it is not the value set for the image. 
So i go to the image page, you will no map as there is no value set.

**Comment by IanMac900** [comment]
I should have said that I have the Category's description switched off at the moment, so that the website user's cannot see the problem.  The problem emerges when this is switched back on.

**Comment by xbgmsharp** [comment]
The issue you describe, is the default behavior on the admin side.
On the user side, you should not see the photo on the map if there is no latitude and longitude set.

**Comment by IanMac900** [comment]
That's made me laugh!  - Sorry to have troubled you - I understand now.
I think it is a very good plug-in - well done in writing it.

**Comment by xbgmsharp** [comment]
Glad it make you laugh! The system has not been design to edit GPS data but gather them from the photo or video and display it on a map.
I update the code to make it easier.

**Comment by IanMac900** [comment]
Thanks
