### ISSUE TITLE
Syntax error admin/admin_config.php

### ISSUE THREAD

**Issue by uwe58** [xbgmsharp/piwigo-openstreetmap#124]
There is a syntax error in admin/admin_config.php:
Line 222:
'mapquestapi'        => $_POST['osm_mapquestapi']),
to
'mapquestapi'        => $_POST['osm_mapquestapi'],

Best, Regards

**Comment by xbgmsharp** [comment]
Oups, sorry, thanks for reporting., fix via e4a137284525cb6651709ae3ee87d20a6f1f7742.
Will release a new version!
