### ISSUE TITLE
the input parameter "min_lat" is not valid

### ISSUE THREAD

**Issue by Romtom03** [xbgmsharp/piwigo-openstreetmap#140]
When I'm on the worldmap, moved around a bit and press then 'Show all' I'll get this error message
`Piwigo encountered an unrecoverable error

[Hacking attempt] the input parameter "min_lat" is not valid

#1	check_input_parameter /piwigo/plugins/piwigo-openstreetmap/include/functions_map.php(145)
#2	osm_get_items /piwigo/plugins/piwigo-openstreetmap/osmmap3.php(92)
#3	include_once /projekte/dietsch/michael/piwigo/osmmap.php(12)`

This happens no matter which map layout I choose.

Did I miss some configuration or did I stumble over a bug?
Thanks for your info
Romtom

**Comment by 7tonin** [comment]
You stumbled over
See commit e138167aacf5c6570e5553d737696391e30cddc1

**Comment by xbgmsharp** [comment]
thanks
