### ISSUE TITLE
Map on Main Page

### ISSUE THREAD

**Issue by 4325123** [xbgmsharp/piwigo-openstreetmap#145]
I just installed the piwigo-openstreetmap and have a strange issue with the map appearing on the main pages.  I've tried a number of settings but it seems like I can't get that map to disappear.  What I want is just the small map in the details section on the right hand side of the picture.

I was wondering if anybody knew of how I can disable the map from appearing on the header portion of the main screens.  An example can be found here.  Thanks in advanced!

![screenshot from 2017-09-20 16-29-19](https://user-images.githubusercontent.com/32146191/30668633-f9cf8a18-9e20-11e7-99bb-97406d569e19.png)

**Comment by evadim** [comment]
Turn off "Category's description" map.

**Comment by 4325123** [comment]
Ah yes, you are correct.  Thank You.
