### ISSUE TITLE
Out of range value for longitude

### ISSUE THREAD

**Issue by samwilson** [xbgmsharp/piwigo-openstreetmap#153]
When trying to save a new place via /admin.php?page=plugin&section=piwigo-openstreetmap%2Fadmin%2Fadmin.php&tab=place I get the following error:

> Warning:  [mysql error 1264] Out of range value for column 'longitude' at row 1
> INSERT INTO `osm_places` (`name`, `latitude`, `longitude`) VALUE ('Rottnest', '-32.0037', '115.5082'); in /var/www/piwigo/include/dblayer/functions_mysqli.inc.php on line 845

**Comment by samwilson** [comment]
I'm assuming this is because the latitude and longitude columns are `double(8,6)` but should be something like `double(9,6)`.

**Comment by xbgmsharp** [comment]
fixed by #156
