### ISSUE TITLE
Missing some translation

### ISSUE THREAD

**Issue by GnunuX** [xbgmsharp/piwigo-openstreetmap#31]
Some string are hard coded like:
'Generated by OSM plugin'
"OSM virtual album\nlat:".$_GET['min_lat']." ".$_GET['max_lat']."\nlng:".$_GET['min_lng']." ".$_GET['max_lng'],
Show items of this screen
Mouse over a cluster to see the bounds of its children and click a cluster to zoom to those bounds

**Comment by xbgmsharp** [comment]
Implemented closing
