### ISSUE TITLE
EDIT_MAP in batch manager

### ISSUE THREAD

**Issue by kjus** [xbgmsharp/piwigo-openstreetmap#45]
Hello!
I use the batch manager a lot. I have edited the files and now I have the Latitude and Longitude boxes available. Is it also possible to fill in those boxes using the map (as in the single photo properties)?
I mean I would love to have a link or button which would open a map, then I click somewhere in the map and the location is grabbed from there.

Thanks

**Comment by xbgmsharp** [comment]
Thanks for the feedback.
It is a good idea, I will see if I can implement it

**Comment by released14** [comment]
Hi, this plugin is getting a wonderful tool, thanks a lot!
Related to this request, would it be possible to enter the coordinates (as numbers) for a set of pictures in the batch manager? I oftentimes have a set of pictures with the same coordinates, and setting them by one by one is very time-consuming for a larger set.
Thanks again!

**Comment by xbgmsharp** [comment]
@released14 If i don't mistake, It is the case already.
The batch manager allow you enter the coordinates (as numbers) for a set of pictures.
You might want to try to use the latest GitHub source.
I need to publish a new release. Maybe today.

**Comment by xbgmsharp** [comment]
@kjus, I can add a map like in photo in the batch manager global mode.
For the batch manager single mode, it is more complex and I don't think a map would help.
What do you think?

**Comment by kjus** [comment]
@xbgmsharp, well, the thing is that in global mode all of the photos have to have the same location. Do I get it right? And I can click the map and set the location this way.
This is also awesome but I more often use the single mode (to add tags after upload) and the photos should have different location each. Is it not possible to implement the map-selector to the single mode batch manager? For each photo separately? Something like "I press the button and the map appears, I click somewhere and the position is saved, the map disappears and that's it"?

**Comment by xbgmsharp** [comment]
It is correct, in global mode all of the photos would have the same location.
Not sure yet if it is technically possible to display a map on the batch manager as the template system of PWG is not the most easier one.
My concern for the the single mode, is how to make it look good!
The map need to big enough but not to take the all page.
I will see if I can come up with something nice.

**Comment by xbgmsharp** [comment]
I integrate a map selection in Batch Manager global and single mode.
Please test and feedback.

**Comment by xbgmsharp** [comment]
Committed and release in v2.7.c https://github.com/xbgmsharp/piwigo-openstreetmap/releases/tag/v2.7.c
Closing
