### ISSUE TITLE
Can we tag several picts at the same time ?

### ISSUE THREAD

**Issue by maviesurmars** [xbgmsharp/piwigo-openstreetmap#47]
Hi 
I'm french so sorry for my english
I discover your plugin which is very cool for piwigo use in my gallery. I'd like to geotag my already uploaded picts but one by one... ouch !! Very fastidious ! A mass geotag is it possible ?

**Comment by xbgmsharp** [comment]
Yes it is possible. The batch manager was drop in early version some how.
You need to use the GitHub source version to use the batch manager mode.
Please refer to the documentation to install it manually, https://github.com/xbgmsharp/piwigo-openstreetmap#installation
It will be include in the next release hopefully soon.

Yesterday, I integrated a map inside the batch to make it even easier.
Feedback is appreciate for this feature. Please refer to issue #45
