### ISSUE TITLE
Even with correct permissions I can't get Open Street Map to work.

### ISSUE THREAD

**Issue by florihupf** [xbgmsharp/piwigo-openstreetmap#49]
I made sure that the piwigo plugins directory is writable by www-data. 

When I delete osmmap.php from the root plugin folder and reconfigure the plugin it still doesn't create this file.

What are the correct steps to install the plugin without creating osmmap.php manually?

**Comment by xbgmsharp** [comment]
Piwigo plugins directory need to be writable to install the plugin.
Piwigo root directory need to writable to create osmmap.php
I will make sure it report an error on write error.

**Comment by florihupf** [comment]
Dang, you are right. I missed the first one.

Thank you!
