### ISSUE TITLE
GPX tracks on the map

### ISSUE THREAD

**Issue by LeOSW42** [xbgmsharp/piwigo-openstreetmap#50]
Hello world

That can be a great feature to attach GPX tracks to a category and display the track on the category map. My categories are all about hikes.

Léo

**Comment by LeOSW42** [comment]
I've seen that page : https://github.com/xbgmsharp/piwigo-openstreetmap/wiki#gpx

But I can't upload GPX files to my server.

Léo

**Comment by xbgmsharp** [comment]
You should upload GPX tracks are per normal photos to PWG. 
Upload your GPX tracks file the PWG way.
This plugin extend PWG support for GPX tracks file.
Each tracks is display as an image item, this mean all GPX tracks file have all PWG features like permission, album, etc...

**Comment by LeOSW42** [comment]
Yes but PWG accepts only PNG, SVG and JPG images, nothing else. I can't
select GPX files in the HTML5 uploader

Le 26/01/2015 12:25, xbgmsharp a écrit :
>
> You should upload GPX tracks are per normal photos to PWG.
> Upload your GPX tracks file the PWG way.
> This plugin extend PWG support for GPX tracks file.
> Each tracks is display as an image item, this mean all GPX tracks file
> have all PWG features like permission, album, etc...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbgmsharp/piwigo-openstreetmap/issues/50#issuecomment-71447274>.
>

-- 
LSTRONIC logo

Léo SERRE
/LSTRONIC Founder/
mail  leo@lstronic.com <mailto:leo@lstronic.com>
website  lstronic.com <http://lsronic.com>

**Comment by xbgmsharp** [comment]
The plugin might not be correctly installed or activated.
Using the "Web Form", in the "Select files" table field, the extension 'gpx' should be list.

If not, use the Localfiles Editor Plugin and added this line to it:
```
    $conf['upload_form_all_types'] = true;
```

Piwigo will let you upload any file matching $conf['file_ext'].

If it works, I will update the documentation.

**Comment by LeOSW42** [comment]
I did that, but after uploading a GPX file, It is not proccessed and I can wait for a long time (infinite)

Léo

**Comment by xbgmsharp** [comment]
Disable other plugin and retry.
If it hangs on upload a plugin is having a conflict.

**Comment by xbgmsharp** [comment]
Any update on this?
Are you able to reproduce the issue?

**Comment by LeOSW42** [comment]
As I said, I wrote my own script for displaying GPX on maps, so I'm not using this one anymore
