### ISSUE TITLE
Separate geoJSON from Categories HTML page

### ISSUE THREAD

**Issue by LeOSW42** [xbgmsharp/piwigo-openstreetmap#51]
Hello,

Is that possible to separate the geoJSON in a separate file ?
Once did, I hope to pass the geoJSON file URL to gpsies for example to display markers on their embedded maps.

Léo

**Comment by xbgmsharp** [comment]
I don't understand what you want. Please be more specific regarding your feature request.
There is geoJSON data, only GPX file which are in XML format and not JSON format.

**Comment by LeOSW42** [comment]
Ok, when I enable Map on Categories, the source code of the page contain the list of the points (images) in the category, in geoJSON :

    var addressPoints = [[42.89805,-0.71657,"DSCN1894.JPG","http://leo.lstronic.com/piwigo/i.php?/upload/2014/08/10/20140810124603-910b2ae6-sq.jpg","http://leo.lstronic.com/piwigo/picture.php?/177/category","","",4608],[42.89773,-0.71747,"DSCN1895.JPG","http://leo.lstronic.com/piwigo/i.php?/upload/2014/08/10/20140810124638-8e17affb-sq.jpg","http://leo.lstronic.com/piwigo/picture.php?/178/category","","",4608]];

It could be great to have that variable externaly (separate file), because I want to use this feed in external maps.

Léo

**Comment by xbgmsharp** [comment]
You can easily make your own. The code to generate JSON data from the database is available here.
https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/include/functions_map.php#L99

I don't see the point to make it as webservice so far, but it can change.

**Comment by LeOSW42** [comment]
Ok I did what I wanted !

Here is an example : http://leo.lstronic.com/piwigo/index.php?/category/9

Léo

**Comment by xbgmsharp** [comment]
Looks very nice
Would like to commit your code so other can use it.

**Comment by LeOSW42** [comment]
Here it is :

https://github.com/LeOSW42/PiwigoImagesAndGPX

Léo
