### ISSUE TITLE
Position of the map in category's description

### ISSUE THREAD

**Issue by piwigoputti** [xbgmsharp/piwigo-openstreetmap#52]
How can the position of the card to be changed? I would have liked to below the categories. The description should remain above the category All thing.

**Comment by xbgmsharp** [comment]
You want to change  the position of the card? What card? Unless you refer to the map.If so which one?
The map in category's description, you want to be able to set it below or upper?

**Comment by piwigoputti** [comment]
Thanks for the quick response. Look SnipFile.

Am 03.02.2015 um 10:24 schrieb xbgmsharp:

**Comment by piwigoputti** [comment]
Thanks for the quick response.
M. Rößmann



Am 03.02.2015 um 10:24 schrieb xbgmsharp:

**Comment by xbgmsharp** [comment]
Please confirm what you are looking for? So I can take a look and I might be able to implement the feature.

**Comment by piwigoputti** [comment]
I have


{if !empty($CONTENT_DESCRIPTION)}
<div class="additional_info">
     {$CONTENT_DESCRIPTION}
</div>
{/if}

moved into the index.tpl the entry to the bottom. Then, however, map and 
text are shifted downwards. The text should stay on top.


So it is now:



That's how it should be:




Am 03.02.2015 um 11:45 schrieb xbgmsharp:

**Comment by xbgmsharp** [comment]
Were you able to make it work by manually editing the file?
If so it will same me time.
You are probably missing you screenshot as there is no image or text for "So it is now:" and "That's how it should be:"
Please show what it is now and what you want.
Even better if you can provide the correct template output.
Then I can work in it.

**Comment by piwigoputti** [comment]
Trying again to send the screenshots.
So it is:
![so it is](https://cloud.githubusercontent.com/assets/10825928/6060152/8e8ea844-ad3a-11e4-8758-970aac92b20d.jpg)

that s how it should be
![that s how it should be](https://cloud.githubusercontent.com/assets/10825928/6060155/9cdcea00-ad3a-11e4-87d9-d430125b1fd0.jpg)

**Comment by xbgmsharp** [comment]
I add a new option to specify the position of the map in category page.
Please test and review.

**Comment by piwigoputti** [comment]
Very good solution. Many Thanks. Also for speed and willingness solution.


Am 11.02.2015 um 17:27 schrieb xbgmsharp:

**Comment by piwigoputti** [comment]
My suggestion for translations:


$lang['WIDTH_DESC'] = 'in Pixeln oder auto'; not automatisch

for the new slider:

Vorschaubild -->Beschreibung oben or: Beschr. oben
Beschreibung -->Beschreibung unten or: Beschr. unten
Letzte Seite -->Kategorie unten or Kateg. unten

**Comment by xbgmsharp** [comment]
Translation are handle by the PWG team.
http://piwigo.org/translate/project.php?project=piwigo_openstreetmap

I try to avoid to create new translation so I used existing one in PWG. Probably not the best idea. I can add new translation word. How would you translate them in English?

**Comment by piwigoputti** [comment]
my english is google-english ....
but PWG use: description (beschreibung), category (kategorie)

Am 12.02.2015 um 15:47 schrieb xbgmsharp:

**Comment by xbgmsharp** [comment]
Done via 9f827b21bb9d274c54c24841dc170753e9f1d86a
Please test and review.

**Comment by xbgmsharp** [comment]
Work completed. Closing.
Please rate my plugin.
