### ISSUE TITLE
Map in Batch Manager cannot search

### ISSUE THREAD

**Issue by juriad** [xbgmsharp/piwigo-openstreetmap#53]
Map in Batch Manager works but it the user cannot search (there is no search button at the right side).
The map is also not height enough (for me), make it heigher or add a config option.

**Comment by xbgmsharp** [comment]
You want to search like in the photo-edit page?
It is hard to make option for the map in Batch Manager, but i look into it.
That is why there is no map customize like the other so far.

**Comment by juriad** [comment]
Yes, the same search.

Regarding he height, I can see there is this declaration in CSS.
```
.map1 {
    height: 200px !important;
...
}
```
If it is too hard to change it, I can do it in my browser by Stylish addon (I am the only admin of my gallery).

**Comment by xbgmsharp** [comment]
As first test, I add new options to specify the height of the Batch Manager map.
Please test and review.
If all fine next the search feature.

**Comment by xbgmsharp** [comment]
I add search feature for BatchManager map.
Please test and review.

**Comment by juriad** [comment]
OK, I have installed the master version and it works really good.

There is just a small problem with the search; sometimes the list of results is too narrow (cropped on the right side). Type in "Melbourne" in the search box and see yourself.
It could easily be fixed by moving the search button to topleft as it is in one of the samples (http://labs.easyblog.it/maps/leaflet-search/examples/simple.html)

Thanks for your effort.

**Comment by xbgmsharp** [comment]
Done via 189127beca7d40ee7e5d0d4c619fb35c97f642cc
Please test and review.

**Comment by xbgmsharp** [comment]
Work completed. Closing.
Please rate my plugin.
