### ISSUE TITLE
Option to turn off bottom photo strip

### ISSUE THREAD

**Issue by jeroenpraat** [xbgmsharp/piwigo-openstreetmap#55]
Hi,

First many thanks for this plugin. Works and looks beautifully

Is it possible to turn off the film strip at the bottom? I don't know if it's related, but Firefox hangs a while when loading the images in this strip. And for me personally the strip is also overkill.

Thanks again,

Jeroen

**Comment by xbgmsharp** [comment]
Hello,

Yes I know it is not the best. I had a few issue with CSS.
I am working on a better integration but still CSS issue.
You can change the version of the WorldMap style by editing a single file.
https://github.com/xbgmsharp/piwigo-openstreetmap/wiki#left-menu-configuration
Using the Git Version there is now an option to do so. It will be include in the next release.

**Comment by jeroenpraat** [comment]
That was not my question. I was asking if the bottom image strip can be disabled? The WorldMap is fine.

**Comment by xbgmsharp** [comment]
It does reply some how.

The first version of the WorldMap does not include the the bottom image strip.
The third version include an option to display or not the bottom image strip.

However if you question, can I disable the bottom image strip on the WorldMap version 2?
Yes you can by editing the template file.

**Comment by jeroenpraat** [comment]
I try to understand what you mean. I changed the WorldMap layout now to osm-map.php on the configuration page. I just wait for the new version of your plugin and will try osm-map3.php than.
