### ISSUE TITLE
Map not displaying under Firefox

### ISSUE THREAD

**Issue by alex3137** [xbgmsharp/piwigo-openstreetmap#57]
Hello.

When I browse my gallery using Firefox (version 37) from both Windows or Mac OS X, the map is not displaying (it is supposed to be located under the "lieu" tag):

![img_0779](https://cloud.githubusercontent.com/assets/6026026/7260455/f95284ea-e861-11e4-839b-7364479e919d.jpg)

If I browse from Safari or Internet Explorer, it displays correctly.

I am using Piwigo 2.7.4 and plugin 2.7.c from Piwigo plugin repository.

Any thoughts ?

**Comment by xbgmsharp** [comment]
It does works fine on my FF. Would you be able to look at ``Inspect Element`` tools include in FF.
Check the ``Console`` log for any error. Which tile do you use? Are in using ``HTTPS`` scheme?
Check the ``Inspector`` tab to check you have the HTML code. 
Check the ``Network`` tab to check, you actually do a request to the tile.
Which theme do you use?

**Comment by alex3137** [comment]
Looks like it is because my site is in https and openstreet map links are http:

From the console:

![img_0805](https://cloud.githubusercontent.com/assets/6026026/7285374/e7708e4a-e93b-11e4-89e6-b423a1c23c74.jpg)

Any way to change the links to https ?

**Comment by xbgmsharp** [comment]
This is the same issue as in #56. See last comment from @Oline.
As your gallery is configure to use HTTP, then PWG function return the HTTP URL. You more likely have PWG in a docker or a VM and server the content via a reverse proxy. 
However I do wonder why you have the issue only with this plugin.
When PWG is configure to use HTTPS is does work fine.

In ``picture.inc.php`` line143,  instead of 
https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/picture.inc.php#L143
```
            'OSM_PATH'         => embellish_url(get_absolute_root_url().OSM_PATH),
```
Do something like:
```
            'OSM_PATH'         => embellish_url(get_gallery_home_url().OSM_PATH),
```
Would you be able to test and feedback?
Works ok on my dev box, if it works for you, I will change across all file and commit the fix.

**Comment by alex3137** [comment]
You are correct, I am using HAProxy as a front-end which handles the https connections. Traffic is http between reverse-proxy and Piwigo VM.

Your fix works for me, thanks a lot !!

**Comment by xbgmsharp** [comment]
I apply the fix on all OSM_PATH via commit cd8dd8b It now provide the PATH and not full URI.

**Comment by bhlevca** [comment]
I have a similar problem being behind ha_proxy.  All the plugins seem to work fine but openstreetmaps do not show in any browser.  

Below is the important lines form the Network tab

```
200     GET site.com	picture.php?/16921/category/297	document html 12.12 kB	66.28 kB	237 ms
blocked GET site.com.	leaflet.js	script		Mixed Block		
blocked GET site.com.	leaflet.js	script		Mixed Block
```

Please let me know what can be done to fix this.

**Comment by bhlevca** [comment]
I have a similar problem with being behind ha_proxy. All the plugins seem to work fine but openstreetmaps do not show in any browser.

Below is the important lines form the Network tab

200     GET site.com	picture.php?/16921/category/297	document html 12.12 kB	66.28 kB	237 ms
blocked GET site.com.	leaflet.js	script		Mixed Block		
blocked GET site.com.	leaflet.js	script		Mixed Block

I am using Piwigo 2.9.5  and plugin 2.9.a from Piwigo plugin repository.

Any thoughts ?
