### ISSUE TITLE
Map only shows when I'm logged in (FF,Opera,Chrome), but does show all the time on IE

### ISSUE THREAD

**Issue by meulie** [xbgmsharp/piwigo-openstreetmap#65]
http://pub.meulie.net/picture/85-01_078_de_waag_te_alkmaar 

This page contains a map, But for those who use Chrome, FF or Opera it only shows when you're logged in.
IE does show the map to non-logged in visitors though.

**Comment by xbgmsharp** [comment]
There is no code base on browser.
Looks like another plugin is generating the issue.
```
<link href="/plugins/piwigo-openstreetmap/leaflet/leaflet.css" rel="stylesheet">
<script data-rocketsrc="/plugins/piwigo-openstreetmap/leaflet/leaflet.js" type="text/rocketscript"></script><style type="text/css">#map{height:300px;}</style>
```
This is ``data-rocketsrc`` is not from the plugin. This come from cloudfare.
http://stackoverflow.com/questions/9681032/why-is-wordpress-placing-text-rocketscript-instead-of-text-javascript-when-u

Try to follow the provided solution.

**Comment by meulie** [comment]
Hmm, the problem persists, even after disabling Rocket Loader for the entire site.

**Comment by xbgmsharp** [comment]
The add_before feature need to visible the guest.
Check https://github.com/xbgmsharp/piwigo-openstreetmap/wiki#add-location-before for details.

**Comment by meulie** [comment]
Yes, that was it!  :)
I switched add_before to a field visible to all, and now it works like a charm. Thanks  :+1: 


(peculiar it worked in IE though...)
