### ISSUE TITLE
Source code contains full descriptions of all images in my album

### ISSUE THREAD

**Issue by meulie** [xbgmsharp/piwigo-openstreetmap#66]
example URL: http://pub.meulie.net/picture/86-01_079_heemskerk_bij_assumburg

When I check out the source for this page I noticed it contains all markers from my entire album. This makes sense of course, because if I were to zoom out on the little map, more markers should show.

It also contains the complete description for all images in the entire album, plus image links.
However... the markers aren't clickable, and only the image title appears when you hover over a marker. So all the image descriptions+URL's are is... overhead?

Is it an idea to exclude image descriptions/url's from these mini-maps?

**Comment by xbgmsharp** [comment]
Are you sing the latest github version?
I guess as this is bug introduce by a change for issue #64

**Comment by meulie** [comment]
Yup, I downloaded the latest version right before reporting this issue  :)

**Comment by xbgmsharp** [comment]
Please revert commit from #64, a quick fix would be to replace in file picture.inc.php on line 129:

$js_data = osm_get_items($page);

by

$js_data = array(array($lat, $lon, null, null, null, null, null, null));

https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/picture.inc.php#L129

**Comment by meulie** [comment]
That does get rid of all the other markers, yes  :)
