### ISSUE TITLE
URL for Mapquest Aerial incorrect?

### ISSUE THREAD

**Issue by ThomasDaheim** [xbgmsharp/piwigo-openstreetmap#79]
Hi,

I have found that using "Mapquest Aerial" no map was shown but only markers & tracks. I had to change the URL in functions_map.php as follows to make it work:
```php
else if($baselayer == 'mapquestaerial') $baselayerurl = 'http://otile1.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.png';
```

**Comment by joubu** [comment]
I have also noticed that on working on #80
