### ISSUE TITLE
gpx files should be .gpx$

### ISSUE THREAD

**Issue by joubu** [xbgmsharp/piwigo-openstreetmap#87]
The osm_get_gps function generates a sql query which retrieves all files containing "gpx".
Instead it should retrieves files with a filename ending with ".gpx".

Otherwise the map won't display anything because of a JS error "TypeError: omnivore.png is not a function" (in the case of a png file).

**Comment by xbgmsharp** [comment]
Pull request merge. Good catch. True it should have been more specific, specially if the filename include GPX. What about uppercase filename?

**Comment by joubu** [comment]
Do you know what is the db collate used by piwigo?
On my install it's utf8_general_ci, so the search is case insensitive.

It seems that there is another place where we should apply the same fix:
admin/admin_batchmanager.php:           $filter = "`path` LIKE '%gpx%'";

**Comment by xbgmsharp** [comment]
Fix and release in v2.8.a
