### ISSUE TITLE
OpenStreentMap plugin right panel issue

### ISSUE THREAD

**Issue by bocman84** [xbgmsharp/piwigo-openstreetmap#92]
Hello!

After reinstallation piwigo I still view map in right panel for old photos, but don't see it for new(imported after reinstallation) photos.
What can I check or configure?

Thank you!

Piwigo 2.7.4/PHP 5.4.44/MySQL 5.6.26

**Comment by xbgmsharp** [comment]
There is no data store or cache by this plugin. Are you sure your new PWG is link to a new database?
Your new imported photos need to include GPS data, you can check the PWG database with latitude and longitude value.

**Comment by xbgmsharp** [comment]
Your data are more likely link to the old database. As mention no data are cache or store anywehere.
It read the DB from the images table.
