### ISSUE TITLE
Width of right panel map

### ISSUE THREAD

**Issue by emja** [xbgmsharp/piwigo-openstreetmap#95]
Hi

The width of the right panel map appears to be limited by any text or objects in the panel. For example, if the only other panel object is 'tags', and there's only the one tag, then the map will be quite narrow. Alternatively, if that same photo has many tags then the map displays wider.

cheers!

**Comment by xbgmsharp** [comment]
Could you try using the latest version available in github? It is not release yet but it does include quite a few fix. https://github.com/xbgmsharp/piwigo-openstreetmap#installation

If the issue still persist, I would need more details to reproduce and fix the issue.
Version of PWG? version of the Plugin? Screenshot? Sample URL?

**Comment by xbgmsharp** [comment]
No reply closing
