### ISSUE TITLE
leaflet-omnivore.min.js is missing

### ISSUE THREAD

**Issue by netchild** [xbgmsharp/piwigo-openstreetmap#96]
Hi,

the browser tries to donwload leaflet-omnivore.min.js which is not included in the plugin-zip on the piwigo extensions page. I downloaded it from github/mapbox and I don't see any issue in my gallery.

Bye,
Alexander.

**Comment by xbgmsharp** [comment]
Confirm in version 2.7.c from http://piwigo.org/ext/extension_view.php?eid=701
``/leaflet/leaflet-omnivore.min.js`` is missing.

However, `leaflet-omnivore.min.js`` is included in the repository. It was add 2 years ago.
https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/leaflet/leaflet-omnivore.min.js

**Comment by xbgmsharp** [comment]
Fix in the latest release, v2.8.a
