### ISSUE TITLE
MapQuest reverse geocoding no longer functional

### ISSUE THREAD

**Issue by lbeltrame** [xbgmsharp/piwigo-openstreetmap#99]
The MapQuest URL used for creating tag groups is no longer working. I had to dig into the PHP code to get why tags weren't being added, and after uncommenting the `print` statement there and checking the URLs manually, I saw

```The AppKey submitted with this request is invalid.```

As a response. So I guess the official OSM service should be used.

**Comment by xbgmsharp** [comment]
Correct since 2015MapQuest require an API KEY. To avoid this issue, I created a NodeJS API proxy, https://github.com/xbgmsharp/nodejs-nominatim however not release yet.  It is a slow work in progress....

**Comment by xbgmsharp** [comment]
It is now committed b66fc4603415d0a364bdff105ae457a6a9fcace0
Please test and feedback, I will make a release soon.

**Comment by xbgmsharp** [comment]
Include in the new release
